[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
dioxus = { workspace = true }
dioxus-fullstack = { workspace = true }
dioxus-web = { workspace = true }
axum = { workspace = true }
